# your domain
domain: wg520.ml

# database url
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files: 
  # use local file
  - ./config/source.yaml
  # use web file
  - https://text1018.herokuapp.com/source.yaml
